services:
  - type: web
    name: mediator-on-call
    runtime: python
    buildCommand: |
      python manage.py migrate
      python manage.py collectstatic --noinput --clear
      chmod +x start.sh
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
