# Generated by Django 5.2.8 on 2026-03-12 21:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100)),
                ('applicant_surname', models.CharField(max_length=100)),
                ('applicant_cell', models.CharField(max_length=20)),
                ('applicant_email', models.EmailField(blank=True, max_length=254)),
                ('respondent_type', models.CharField(choices=[('ind', 'Individual'), ('bus', 'Business')], max_length=10)),
                ('respondent_name', models.CharField(blank=True, max_length=100)),
                ('respondent_surname', models.CharField(blank=True, max_length=100)),
                ('respondent_cell', models.CharField(blank=True, max_length=20)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('owner_name', models.CharField(blank=True, max_length=100)),
                ('owner_surname', models.CharField(blank=True, max_length=100)),
                ('business_cell', models.CharField(blank=True, max_length=20)),
                ('respondent_email', models.EmailField(blank=True, max_length=254)),
                ('dispute_type', models.CharField(choices=[('family', 'Family'), ('labour', 'Labour'), ('property', 'Property')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('screening', 'Under Screening'), ('rejected', 'Rejected - Not Mediatable'), ('forwarded', 'Forwarded to Respondent'), ('responded', 'Respondent Responded'), ('mediation_scheduled', 'Mediation Scheduled'), ('mediated', 'Mediation Completed'), ('closed', 'Closed'), ('arbitration', 'Referred to Arbitration')], default='submitted', max_length=20)),
                ('is_mediatable', models.BooleanField(blank=True, null=True)),
                ('screening_notes', models.TextField(blank=True)),
                ('screened_at', models.DateTimeField(blank=True, null=True)),
                ('respondent_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('token_created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant_view_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('screened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screened_disputes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='disputes.dispute')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DisputeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dispute_docs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='disputes.dispute')),
            ],
        ),
        migrations.CreateModel(
            name='Mediator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('zoom_link', models.URLField()),
                ('outcome', models.TextField(blank=True)),
                ('outcome_file', models.FileField(blank=True, upload_to='outcomes/')),
                ('arbitration_agreement', models.FileField(blank=True, upload_to='arbitration/')),
                ('pre_arbitration_minute', models.FileField(blank=True, upload_to='arbitration/')),
                ('dispute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mediation', to='disputes.dispute')),
                ('mediator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='disputes.mediator')),
            ],
        ),
        migrations.CreateModel(
            name='RespondentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_to_mediate', models.BooleanField(default=False)),
                ('agreed_to_rules', models.BooleanField(default=False)),
                ('defence_explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='disputes.dispute')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='response_docs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='disputes.respondentresponse')),
            ],
        ),
    ]
