# Generated by Django 5.2.8 on 2026-03-13 21:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0002_alter_mediator_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespondentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respondent_tokens', to='disputes.dispute')),
            ],
        ),
    ]
