# Generated by Django 5.2.8 on 2026-03-16 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0003_respondenttoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediatableCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('accepted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediatable_cases', to=settings.AUTH_USER_MODEL)),
                ('dispute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mediatable_case', to='disputes.dispute')),
            ],
        ),
        migrations.CreateModel(
            name='ReferredCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_to', models.CharField(choices=[('legal', 'Legal Aid'), ('court', 'Court'), ('police', 'Police'), ('labour', 'Labour Department'), ('family', 'Family Services'), ('foresolve', 'Foresolve'), ('other', 'Other')], max_length=20)),
                ('referred_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('referral_details', models.TextField(blank=True)),
                ('dispute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_case', to='disputes.dispute')),
                ('referred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
