# Generated by Django 5.2.8 on 2026-03-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0004_mediatablecase_referredcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='photo',
            field=models.ImageField(blank=True, help_text='Take a photo to support your dispute', null=True, upload_to='dispute_photos/'),
        ),
    ]
