# Generated by Django 5.2.8 on 2026-03-17 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0005_dispute_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='applicant_amended_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='applicant_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='mediator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_disputes', to='disputes.mediator'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='mediator_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='respondent_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='respondent_response_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('screening', 'Under Screening'), ('rejected', 'Rejected - Not Mediatable'), ('mediator_assigned', 'Mediator Assigned - Awaiting Applicant Confirmation'), ('applicant_confirmed', 'Applicant Confirmed - Awaiting Respondent'), ('forwarded', 'Forwarded to Respondent'), ('responded', 'Respondent Responded'), ('mediation_scheduled', 'Mediation Scheduled'), ('mediated', 'Mediation Completed'), ('closed', 'Closed'), ('arbitration', 'Referred to Arbitration'), ('respondent_no_response', 'Respondent No Response')], default='submitted', max_length=30),
        ),
    ]
