# Generated by Django 5.2.8 on 2026-03-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0006_dispute_applicant_amended_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='applicant_final_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='respondent_agreed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('screening', 'Under Screening'), ('rejected', 'Rejected - Not Mediatable'), ('mediator_assigned', 'Mediator Assigned - Awaiting Applicant Confirmation'), ('applicant_confirmed', 'Applicant Confirmed - Awaiting Respondent'), ('forwarded', 'Forwarded to Respondent'), ('responded', 'Respondent Responded'), ('respondent_agreed', 'Respondent Agreed - Awaiting Applicant Final Confirmation'), ('ready_for_assignment', 'Ready for Mediator Assignment'), ('mediator_assigned', 'Mediator Assigned'), ('mediation_scheduled', 'Mediation Scheduled'), ('mediated', 'Mediation Completed'), ('closed', 'Closed'), ('arbitration', 'Referred to Arbitration'), ('respondent_no_response', 'Respondent No Response')], default='submitted', max_length=30),
        ),
    ]
