# Generated by Django 5.2.8 on 2026-03-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0007_dispute_applicant_final_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='mediation_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dispute',
            name='preferred_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
