# Generated by Django 5.2.8 on 2026-03-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0008_dispute_mediation_location_dispute_preferred_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='dispute_type',
            field=models.CharField(choices=[('civil', 'Civil'), ('commercial', 'Commercial'), ('community', 'Community'), ('construction', 'Construction'), ('contractual', 'Contractual'), ('criminal', 'Criminal'), ('customary', 'Customary'), ('damages', 'Damages'), ('debts', 'Debts'), ('divorce', 'Divorce'), ('family', 'Family'), ('labour', 'Labour'), ('lease', 'Lease'), ('loans', 'Loans'), ('property', 'Property'), ('religion', 'Religion'), ('sales', 'Sales')], max_length=20),
        ),
    ]
