# Generated by Django 5.2.8 on 2026-04-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0011_calendar_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
