# Generated by Django 5.2.8 on 2026-04-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0012_dispute_deleted_at_dispute_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarnote',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarnote',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
