# Generated by Django 5.2.15 on 2026-06-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0014_mediationsession_host_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('screening', 'Under Screening'), ('rejected', 'Rejected - Not Mediatable'), ('mediator_assigned', 'Mediator Assigned'), ('applicant_confirmed', 'Applicant Confirmed - Awaiting Respondent'), ('forwarded', 'Forwarded to Respondent'), ('responded', 'Respondent Responded'), ('respondent_agreed', 'Respondent Agreed - Awaiting Applicant Final Confirmation'), ('ready_for_assignment', 'Ready for Mediator Assignment'), ('mediation_scheduled', 'Mediation Scheduled'), ('mediated', 'Mediation Completed'), ('closed', 'Closed'), ('arbitration', 'Referred to Arbitration'), ('respondent_no_response', 'Respondent No Response')], default='submitted', max_length=30),
        ),
    ]
